title: stupid dumb student that can't write a code
author: me(who does not study properly)
email: psionic3735@dgu.ac.kr
description: > # this means to ignore newlines until "baseurl:"
  don't know how long this could be so good

# social links
twitter_username: cant open my twitter its in abyss  # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
